Wuix pr
wuixwui/first-repo pull request #1
Opened 2021-07-21 12:06 UTC by wuixwui

### introduce.html
---
use `<div>` and `<p>` tag for describing me

2021-07-21 13:04 UTC, dan9708 requested changes

2021-07-21 13:30 UTC, wuixwui commented on introduce.html
> +<body>
**wow** that's a good idea!!  i will try right now 👍

2021-07-21 13:37 UTC, wuixwui commented on introduce.html
> +	<div id="name">name: Seo Woori</div>
Hmm.. I don't understand well... anyway I think you mean reduce category to number of three! is it right? i will try~

2021-07-22 04:35 UTC, dan9708 commented on introduce.html
> +	<div id="name">name: Seo Woori</div>
마자요 ~ div갯수를 3개로 줄이면 좋을거같다고 작성했습니다.

2021-07-22 05:07 UTC, dan9708 approved these changes

2021-07-22 05:15 UTC, merged